from enum import Enum


class RuleType(str, Enum):
    VISA = "VISA"
    PASSPORT = "PASSPORT"
    TRAVEL_AUTHORIZATION = "TRAVEL_AUTHORIZATION"
    TRANSIT = "TRANSIT"
    HEALTH = "HEALTH"
    CUSTOMS = "CUSTOMS"
    IMMIGRATION = "IMMIGRATION"
    ENTRY_RESTRICTION = "ENTRY_RESTRICTION"