"""create visa_types table

Revision ID: 25492df4d22d
Revises: 2cb258dc5d50
Create Date: 2026-07-22 10:23:57.266455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25492df4d22d'
down_revision: Union[str, Sequence[str], None] = '2cb258dc5d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visa_types',
    sa.Column('visa_code', sa.String(length=10), nullable=False),
    sa.Column('visa_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visa_code')
    )
    op.create_index(op.f('ix_visa_types_id'), 'visa_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visa_types_id'), table_name='visa_types')
    op.drop_table('visa_types')
    # ### end Alembic commands ###
