"""create passport_types table

Revision ID: 2cb258dc5d50
Revises: 7b8b3141d17e
Create Date: 2026-07-22 10:11:37.856816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb258dc5d50'
down_revision: Union[str, Sequence[str], None] = '7b8b3141d17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passport_types',
    sa.Column('passport_code', sa.String(length=10), nullable=False),
    sa.Column('passport_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passport_code')
    )
    op.create_index(op.f('ix_passport_types_id'), 'passport_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passport_types_id'), table_name='passport_types')
    op.drop_table('passport_types')
    # ### end Alembic commands ###
