"""Update compliance rule relationships

Revision ID: 44c4aa8e5a5d
Revises: d23e8a84457a
Create Date: 2026-08-05 10:24:11.534940

"""
from typing import Sequence, Union

from alembic import op
#import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c4aa8e5a5d'
down_revision: Union[str, Sequence[str], None] = 'd23e8a84457a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('customs_rules_rule_id_key'), 'customs_rules', type_='unique')
    op.drop_constraint(op.f('entry_restrictions_rule_id_key'), 'entry_restrictions', type_='unique')
    op.drop_constraint(op.f('health_rules_rule_id_key'), 'health_rules', type_='unique')
    op.drop_constraint(op.f('immigration_rules_rule_id_key'), 'immigration_rules', type_='unique')
    op.drop_constraint(op.f('passport_rules_rule_id_key'), 'passport_rules', type_='unique')
    op.drop_constraint(op.f('transit_rules_rule_id_key'), 'transit_rules', type_='unique')
    op.drop_constraint(op.f('travel_authorization_rules_rule_id_key'), 'travel_authorization_rules', type_='unique')
    op.drop_constraint(op.f('visa_rules_rule_id_key'), 'visa_rules', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('visa_rules_rule_id_key'), 'visa_rules', ['rule_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('travel_authorization_rules_rule_id_key'), 'travel_authorization_rules', ['rule_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('transit_rules_rule_id_key'), 'transit_rules', ['rule_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('passport_rules_rule_id_key'), 'passport_rules', ['rule_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('immigration_rules_rule_id_key'), 'immigration_rules', ['rule_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('health_rules_rule_id_key'), 'health_rules', ['rule_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('entry_restrictions_rule_id_key'), 'entry_restrictions', ['rule_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customs_rules_rule_id_key'), 'customs_rules', ['rule_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
