"""create currencies table

Revision ID: 5a170994dd6b
Revises: 601c91c9e19d
Create Date: 2026-07-21 14:22:39.693186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a170994dd6b'
down_revision: Union[str, Sequence[str], None] = '601c91c9e19d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('currency_name', sa.String(length=100), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code')
    )
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
