"""create passenger_types table

Revision ID: 64e8e0ca72b8
Revises: c7c23d335a55
Create Date: 2026-07-22 10:34:59.541669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e8e0ca72b8'
down_revision: Union[str, Sequence[str], None] = 'c7c23d335a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passenger_types',
    sa.Column('passenger_type_code', sa.String(length=20), nullable=False),
    sa.Column('passenger_type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passenger_type_code')
    )
    op.create_index(op.f('ix_passenger_types_id'), 'passenger_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passenger_types_id'), table_name='passenger_types')
    op.drop_table('passenger_types')
    # ### end Alembic commands ###
