"""add audit columns to health_rule_vaccines

Revision ID: 739df2019ba2
Revises: b3d0e9a68ad5
Create Date: 2026-08-03 16:11:06.047478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739df2019ba2'
down_revision: Union[str, Sequence[str], None] = 'b3d0e9a68ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_rule_vaccines', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('health_rule_vaccines', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('health_rule_vaccines', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_health_rule_vaccines_id'), 'health_rule_vaccines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_rule_vaccines_id'), table_name='health_rule_vaccines')
    op.drop_column('health_rule_vaccines', 'updated_at')
    op.drop_column('health_rule_vaccines', 'created_at')
    op.drop_column('health_rule_vaccines', 'active')
    # ### end Alembic commands ###
