"""Initial schema

Revision ID: 73cd664090df
Revises: 
Create Date: 2026-07-31 11:44:28.469325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73cd664090df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('client_code', sa.String(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('subscription_plan', sa.Enum('STANDARD', 'PREMIUM', 'ENTERPRISE', name='subscription_plan_enum'), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_code')
    )
    op.create_index(op.f('ix_api_clients_id'), 'api_clients', ['id'], unique=False)
    op.create_table('currencies',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('currency_name', sa.String(length=100), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code')
    )
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_table('passenger_types',
    sa.Column('passenger_type_code', sa.String(length=20), nullable=False),
    sa.Column('passenger_type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passenger_type_code')
    )
    op.create_index(op.f('ix_passenger_types_id'), 'passenger_types', ['id'], unique=False)
    op.create_table('passport_types',
    sa.Column('passport_code', sa.String(length=10), nullable=False),
    sa.Column('passport_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passport_code')
    )
    op.create_index(op.f('ix_passport_types_id'), 'passport_types', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.Column('permission_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_code')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('purposes',
    sa.Column('purpose_code', sa.String(length=20), nullable=False),
    sa.Column('purpose_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purpose_code')
    )
    op.create_index(op.f('ix_purposes_id'), 'purposes', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_name')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('rule_statuses',
    sa.Column('status_code', sa.String(length=20), nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_code')
    )
    op.create_index(op.f('ix_rule_statuses_id'), 'rule_statuses', ['id'], unique=False)
    op.create_table('vaccines',
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('disease', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccines_id'), 'vaccines', ['id'], unique=False)
    op.create_table('visa_types',
    sa.Column('visa_code', sa.String(length=10), nullable=False),
    sa.Column('visa_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visa_code')
    )
    op.create_index(op.f('ix_visa_types_id'), 'visa_types', ['id'], unique=False)
    op.create_table('api_request_logs',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('http_method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', name='httpmethod'), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['api_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_request_logs_id'), 'api_request_logs', ['id'], unique=False)
    op.create_table('client_ip_whitelists',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('cidr_range', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['api_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_ip_whitelists_id'), 'client_ip_whitelists', ['id'], unique=False)
    op.create_table('client_usage_statistics',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('average_response_time', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['api_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'usage_date', name='uq_client_usage_date')
    )
    op.create_index(op.f('ix_client_usage_statistics_id'), 'client_usage_statistics', ['id'], unique=False)
    op.create_table('countries',
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('capital', sa.String(length=100), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('official_language', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso2'),
    sa.UniqueConstraint('iso3')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('airlines',
    sa.Column('airline_name', sa.String(length=150), nullable=False),
    sa.Column('iata_code', sa.String(length=2), nullable=True),
    sa.Column('icao_code', sa.String(length=3), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='fk_airlines_country_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code'),
    sa.UniqueConstraint('icao_code')
    )
    op.create_index(op.f('ix_airlines_id'), 'airlines', ['id'], unique=False)
    op.create_table('airports',
    sa.Column('iata_code', sa.String(length=3), nullable=True),
    sa.Column('icao_code', sa.String(length=4), nullable=True),
    sa.Column('airport_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('international', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='fk_airports_country_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code'),
    sa.UniqueConstraint('icao_code')
    )
    op.create_index(op.f('ix_airports_id'), 'airports', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('INSERT', 'UPDATE', 'DELETE', name='auditaction'), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('source_registry',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('authority_name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('API', 'WEBSITE', 'PDF', 'EMAIL', name='sourcetype'), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('update_frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'ON_DEMAND', name='updatefrequency'), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_registry_id'), 'source_registry', ['id'], unique=False)
    op.create_table('travel_authorizations',
    sa.Column('authorization_code', sa.String(length=20), nullable=False),
    sa.Column('authorization_name', sa.String(length=150), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], name='fk_travel_authorizations_destination_country_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_code')
    )
    op.create_index(op.f('ix_travel_authorizations_id'), 'travel_authorizations', ['id'], unique=False)
    op.create_table('collection_logs',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('collection_type', sa.Enum('MANUAL', 'API', 'CRAWLER', name='collectiontype'), nullable=False),
    sa.Column('collection_status', sa.Enum('SUCCESS', 'FAILED', name='collectionstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_logs_id'), 'collection_logs', ['id'], unique=False)
    op.create_table('rules',
    sa.Column('rule_code', sa.String(length=30), nullable=False),
    sa.Column('rule_type', sa.Enum('VISA', 'PASSPORT', 'TRAVEL_AUTHORIZATION', 'TRANSIT', 'HEALTH', 'CUSTOMS', 'IMMIGRATION', 'ENTRY_RESTRICTION', name='rule_type_enum'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='3', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['rule_statuses.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_index(op.f('ix_rules_rule_code'), 'rules', ['rule_code'], unique=True)
    op.create_table('source_documents',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('PDF', 'HTML', 'API_RESPONSE', name='documenttype'), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=255), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_id'), 'source_documents', ['id'], unique=False)
    op.create_table('ai_extractions',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('extraction_engine', sa.String(length=100), nullable=False),
    sa.Column('extraction_status', sa.Enum('SUCCESS', 'FAILED', name='extractionstatus'), nullable=False),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_extractions_id'), 'ai_extractions', ['id'], unique=False)
    op.create_table('customs_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('nationality_country_id', sa.Integer(), nullable=False),
    sa.Column('alcohol_limit', sa.Text(), nullable=True),
    sa.Column('tobacco_limit', sa.Text(), nullable=True),
    sa.Column('currency_limit_amount', sa.Numeric(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('currency_declaration_required', sa.Boolean(), nullable=False),
    sa.Column('medication_rules', sa.Text(), nullable=True),
    sa.Column('prohibited_items', sa.Text(), nullable=True),
    sa.Column('restricted_items', sa.Text(), nullable=True),
    sa.Column('pet_import_rules', sa.Text(), nullable=True),
    sa.Column('condition_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exemption_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['nationality_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_table('document_validations',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('validator_id', sa.Integer(), nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='validationstatus'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['validator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_validations_id'), 'document_validations', ['id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('file_hash', sa.String(length=255), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_id'), 'document_versions', ['id'], unique=False)
    op.create_table('entry_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('nationality_country_id', sa.Integer(), nullable=False),
    sa.Column('restriction_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('condition_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['nationality_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_table('health_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('nationality_country_id', sa.Integer(), nullable=False),
    sa.Column('health_form_required', sa.Boolean(), nullable=False),
    sa.Column('quarantine_required', sa.Boolean(), nullable=False),
    sa.Column('quarantine_days', sa.Integer(), nullable=True),
    sa.Column('medical_certificate_required', sa.Boolean(), nullable=False),
    sa.Column('condition_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exemption_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['nationality_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_table('immigration_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('onward_ticket_required', sa.Boolean(), nullable=False),
    sa.Column('accommodation_proof_required', sa.Boolean(), nullable=False),
    sa.Column('proof_of_funds_required', sa.Boolean(), nullable=False),
    sa.Column('biometric_required', sa.Boolean(), nullable=False),
    sa.Column('interview_required', sa.Boolean(), nullable=False),
    sa.Column('arrival_card_required', sa.Boolean(), nullable=False),
    sa.Column('digital_arrival_card', sa.Boolean(), nullable=False),
    sa.Column('arrival_registration_required', sa.Boolean(), nullable=False),
    sa.Column('condition_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exemption_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_table('passport_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('passport_type_id', sa.Integer(), nullable=False),
    sa.Column('minimum_validity_months', sa.Integer(), nullable=True),
    sa.Column('blank_pages_required', sa.Integer(), nullable=True),
    sa.Column('machine_readable_required', sa.Boolean(), nullable=True),
    sa.Column('damaged_passport_allowed', sa.Boolean(), nullable=True),
    sa.Column('temporary_passport_allowed', sa.Boolean(), nullable=True),
    sa.Column('passport_issue_date_required', sa.Boolean(), nullable=True),
    sa.Column('condition_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exemption_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['passport_type_id'], ['passport_types.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_index(op.f('ix_passport_rules_id'), 'passport_rules', ['id'], unique=False)
    op.create_table('rule_approvals',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.Enum('APPROVED', 'REJECTED', name='approval_status_enum'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_approvals_id'), 'rule_approvals', ['id'], unique=False)
    op.create_table('rule_execution_logs',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_execution_logs_id'), 'rule_execution_logs', ['id'], unique=False)
    op.create_table('rule_versions',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_versions_id'), 'rule_versions', ['id'], unique=False)
    op.create_table('transit_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('nationality_country_id', sa.Integer(), nullable=False),
    sa.Column('transit_country_id', sa.Integer(), nullable=False),
    sa.Column('transit_airport_id', sa.Integer(), nullable=False),
    sa.Column('transit_visa_required', sa.Boolean(), nullable=False),
    sa.Column('airside_transit_allowed', sa.Boolean(), nullable=False),
    sa.Column('baggage_collection_required', sa.Boolean(), nullable=False),
    sa.Column('overnight_transit_allowed', sa.Boolean(), nullable=False),
    sa.Column('max_transit_hours', sa.Integer(), nullable=True),
    sa.Column('condition_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exemption_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nationality_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['transit_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['transit_country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_index(op.f('ix_transit_rules_id'), 'transit_rules', ['id'], unique=False)
    op.create_table('travel_authorization_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('authorization_id', sa.Integer(), nullable=False),
    sa.Column('nationality_country_id', sa.Integer(), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('passport_type_id', sa.Integer(), nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('authorization_required', sa.Boolean(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('condition_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exemption_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authorization_id'], ['travel_authorizations.id'], name='fk_travel_authorization_rules_authorization_id'),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], name='fk_travel_authorization_rules_destination_country_id'),
    sa.ForeignKeyConstraint(['nationality_country_id'], ['countries.id'], name='fk_travel_authorization_rules_nationality_country_id'),
    sa.ForeignKeyConstraint(['passport_type_id'], ['passport_types.id'], name='fk_travel_authorization_rules_passport_type_id'),
    sa.ForeignKeyConstraint(['purpose_id'], ['purposes.id'], name='fk_travel_authorization_rules_purpose_id'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name='fk_travel_authorization_rules_rule_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_index(op.f('ix_travel_authorization_rules_id'), 'travel_authorization_rules', ['id'], unique=False)
    op.create_table('visa_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('nationality_country_id', sa.Integer(), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('passport_type_id', sa.Integer(), nullable=False),
    sa.Column('visa_type_id', sa.Integer(), nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('visa_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('visa_on_arrival', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('evisa_available', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('max_stay_days', sa.Integer(), nullable=True),
    sa.Column('multiple_entry', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('condition_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exemption_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['nationality_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['passport_type_id'], ['passport_types.id'], ),
    sa.ForeignKeyConstraint(['purpose_id'], ['purposes.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['visa_type_id'], ['visa_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_index(op.f('ix_visa_rules_id'), 'visa_rules', ['id'], unique=False)
    op.create_index('ix_visa_rules_nationality_destination', 'visa_rules', ['nationality_country_id', 'destination_country_id'], unique=False)
    op.create_index('ix_visa_rules_passport_type', 'visa_rules', ['passport_type_id'], unique=False)
    op.create_index('ix_visa_rules_purpose', 'visa_rules', ['purpose_id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('ALLOWED', 'CONDITIONAL', 'NOT_ALLOWED', name='decision'), nullable=False),
    sa.Column('decision_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['api_clients.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_compliance_checks_id'), 'compliance_checks', ['id'], unique=False)
    op.create_table('health_rule_vaccines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_rule_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('certificate_required', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['health_rule_id'], ['health_rules.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_history',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.Column('new_version_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'PUBLISH', 'EXPIRE', name='change_type_enum'), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_version_id'], ['rule_versions.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['rule_versions.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_history_id'), 'rule_history', ['id'], unique=False)
    op.create_table('rule_simulations',
    sa.Column('simulation_name', sa.String(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('expected_result', sa.JSON(), nullable=False),
    sa.Column('actual_result', sa.JSON(), nullable=True),
    sa.Column('simulation_status', sa.Enum('PASSED', 'FAILED', 'ERROR', name='simulation_status_enum'), nullable=False),
    sa.Column('executed_by', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_simulations_id'), 'rule_simulations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_simulations_id'), table_name='rule_simulations')
    op.drop_table('rule_simulations')
    op.drop_index(op.f('ix_rule_history_id'), table_name='rule_history')
    op.drop_table('rule_history')
    op.drop_table('health_rule_vaccines')
    op.drop_index(op.f('ix_compliance_checks_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index('ix_visa_rules_purpose', table_name='visa_rules')
    op.drop_index('ix_visa_rules_passport_type', table_name='visa_rules')
    op.drop_index('ix_visa_rules_nationality_destination', table_name='visa_rules')
    op.drop_index(op.f('ix_visa_rules_id'), table_name='visa_rules')
    op.drop_table('visa_rules')
    op.drop_index(op.f('ix_travel_authorization_rules_id'), table_name='travel_authorization_rules')
    op.drop_table('travel_authorization_rules')
    op.drop_index(op.f('ix_transit_rules_id'), table_name='transit_rules')
    op.drop_table('transit_rules')
    op.drop_index(op.f('ix_rule_versions_id'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_rule_execution_logs_id'), table_name='rule_execution_logs')
    op.drop_table('rule_execution_logs')
    op.drop_index(op.f('ix_rule_approvals_id'), table_name='rule_approvals')
    op.drop_table('rule_approvals')
    op.drop_index(op.f('ix_passport_rules_id'), table_name='passport_rules')
    op.drop_table('passport_rules')
    op.drop_table('immigration_rules')
    op.drop_table('health_rules')
    op.drop_table('entry_restrictions')
    op.drop_index(op.f('ix_document_versions_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_validations_id'), table_name='document_validations')
    op.drop_table('document_validations')
    op.drop_table('customs_rules')
    op.drop_index(op.f('ix_ai_extractions_id'), table_name='ai_extractions')
    op.drop_table('ai_extractions')
    op.drop_index(op.f('ix_source_documents_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_rules_rule_code'), table_name='rules')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_collection_logs_id'), table_name='collection_logs')
    op.drop_table('collection_logs')
    op.drop_index(op.f('ix_travel_authorizations_id'), table_name='travel_authorizations')
    op.drop_table('travel_authorizations')
    op.drop_index(op.f('ix_source_registry_id'), table_name='source_registry')
    op.drop_table('source_registry')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_airports_id'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_airlines_id'), table_name='airlines')
    op.drop_table('airlines')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_client_usage_statistics_id'), table_name='client_usage_statistics')
    op.drop_table('client_usage_statistics')
    op.drop_index(op.f('ix_client_ip_whitelists_id'), table_name='client_ip_whitelists')
    op.drop_table('client_ip_whitelists')
    op.drop_index(op.f('ix_api_request_logs_id'), table_name='api_request_logs')
    op.drop_table('api_request_logs')
    op.drop_index(op.f('ix_visa_types_id'), table_name='visa_types')
    op.drop_table('visa_types')
    op.drop_index(op.f('ix_vaccines_id'), table_name='vaccines')
    op.drop_table('vaccines')
    op.drop_index(op.f('ix_rule_statuses_id'), table_name='rule_statuses')
    op.drop_table('rule_statuses')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_purposes_id'), table_name='purposes')
    op.drop_table('purposes')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_passport_types_id'), table_name='passport_types')
    op.drop_table('passport_types')
    op.drop_index(op.f('ix_passenger_types_id'), table_name='passenger_types')
    op.drop_table('passenger_types')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_api_clients_id'), table_name='api_clients')
    op.drop_table('api_clients')
    # ### end Alembic commands ###
