"""add audit columns to immigration_rules

Revision ID: 7a783d021844
Revises: 73cd664090df
Create Date: 2026-08-03 15:24:37.852656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a783d021844'
down_revision: Union[str, Sequence[str], None] = '73cd664090df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('immigration_rules', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('immigration_rules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('immigration_rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_immigration_rules_id'), 'immigration_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_immigration_rules_id'), table_name='immigration_rules')
    op.drop_column('immigration_rules', 'updated_at')
    op.drop_column('immigration_rules', 'created_at')
    op.drop_column('immigration_rules', 'active')
    # ### end Alembic commands ###
