"""add region and currency foreign keys to countries

Revision ID: 7b8b3141d17e
Revises: 5a170994dd6b
Create Date: 2026-07-21 15:00:58.351243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8b3141d17e'
down_revision: Union[str, Sequence[str], None] = '5a170994dd6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('region_id', sa.Integer(), nullable=False))
    op.add_column('countries', sa.Column('currency_id', sa.Integer(), nullable=False))
    op.alter_column('countries', 'capital',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('countries', 'official_language',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('countries', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('countries_country_name_key'), 'countries', type_='unique')
    op.create_foreign_key("fk_countries_currency_id", 'countries', 'currencies', ['currency_id'], ['id'])
    op.create_foreign_key("fk_countries_region_id", 'countries', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_countries_region_id", 'countries', type_='foreignkey')
    op.drop_constraint("fk_countries_currency_id", 'countries', type_='foreignkey')
    op.create_unique_constraint(op.f('countries_country_name_key'), 'countries', ['country_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('countries', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('countries', 'official_language',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('countries', 'capital',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('countries', 'currency_id')
    op.drop_column('countries', 'region_id')
    # ### end Alembic commands ###
