"""add audit columns to health_rules

Revision ID: b3d0e9a68ad5
Revises: 7a783d021844
Create Date: 2026-08-03 15:50:30.124350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d0e9a68ad5'
down_revision: Union[str, Sequence[str], None] = '7a783d021844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_rules', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('health_rules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('health_rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_health_rules_id'), 'health_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_rules_id'), table_name='health_rules')
    op.drop_column('health_rules', 'updated_at')
    op.drop_column('health_rules', 'created_at')
    op.drop_column('health_rules', 'active')
    # ### end Alembic commands ###
