"""create purposes table

Revision ID: c7c23d335a55
Revises: 25492df4d22d
Create Date: 2026-07-22 10:29:56.988706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c23d335a55'
down_revision: Union[str, Sequence[str], None] = '25492df4d22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purposes',
    sa.Column('purpose_code', sa.String(length=20), nullable=False),
    sa.Column('purpose_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purpose_code')
    )
    op.create_index(op.f('ix_purposes_id'), 'purposes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purposes_id'), table_name='purposes')
    op.drop_table('purposes')
    # ### end Alembic commands ###
