"""add audit columns to customs_rules

Revision ID: d23e8a84457a
Revises: cf88843e2192
Create Date: 2026-08-03 16:36:39.771207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23e8a84457a'
down_revision: Union[str, Sequence[str], None] = 'cf88843e2192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customs_rules', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('customs_rules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('customs_rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_customs_rules_id'), 'customs_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customs_rules_id'), table_name='customs_rules')
    op.drop_column('customs_rules', 'updated_at')
    op.drop_column('customs_rules', 'created_at')
    op.drop_column('customs_rules', 'active')
    # ### end Alembic commands ###
