"""create travel_authorizations table

Revision ID: d3cef20e438e
Revises: 64e8e0ca72b8
Create Date: 2026-07-22 10:41:27.199403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cef20e438e'
down_revision: Union[str, Sequence[str], None] = '64e8e0ca72b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_authorizations',
    sa.Column('authorization_code', sa.String(length=20), nullable=False),
    sa.Column('authorization_name', sa.String(length=150), nullable=False),
    sa.Column('destination_country_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_country_id'], ['countries.id'], name='fk_travel_authorizations_destination_country_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_code')
    )
    op.create_index(op.f('ix_travel_authorizations_id'), 'travel_authorizations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_authorizations_id'), table_name='travel_authorizations')
    op.drop_table('travel_authorizations')
    # ### end Alembic commands ###
