"""create airlines table

Revision ID: da24a3b12228
Revises: d3cef20e438e
Create Date: 2026-07-22 11:02:14.067449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da24a3b12228'
down_revision: Union[str, Sequence[str], None] = 'd3cef20e438e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('airline_name', sa.String(length=150), nullable=False),
    sa.Column('iata_code', sa.String(length=2), nullable=True),
    sa.Column('icao_code', sa.String(length=3), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='fk_airlines_country_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code'),
    sa.UniqueConstraint('icao_code')
    )
    op.create_index(op.f('ix_airlines_id'), 'airlines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airlines_id'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
