"""API key generation/hashing for the client self-service portal.

Why this isn't just bcrypt (like passwords in security.py):
    Passwords are short, low-entropy, human-chosen secrets -- bcrypt's
    slow, salted hashing is what makes brute-forcing them impractical.
    An API key here is the opposite: 32 bytes (256 bits) of
    os.urandom, generated by us. It already has more entropy than any
    hash could add protection against, so the standard pattern used by
    Stripe/GitHub/OpenAI et al. is a fast, *deterministic* hash
    (SHA-256) -- deterministic on purpose, because it lets us look the
    key up by its hash directly in a `WHERE api_key_hash = :hash`
    query instead of loading every row and calling verify_password on
    each one.

    The plaintext key is only ever known at the moment it's generated.
    From then on we store: a hash (for lookup/verification), a short
    prefix (safe to show in a UI, e.g. "tac_live_9f3a"), and the last
    4 characters (so a client can recognise "is this the key I think
    it is" without us ever storing or re-displaying the full value).
"""

import hashlib
import secrets

_KEY_PREFIX = "tac_live"
_PREFIX_VISIBLE_CHARS = 4  # how many random chars are shown unmasked


def generate_api_key() -> str:
    """Generate a new plaintext API key.

    Format: tac_live_<43 url-safe base64 chars, ~32 bytes of entropy>
    Shown to the client exactly once, at creation time.
    """
    return f"{_KEY_PREFIX}_{secrets.token_urlsafe(32)}"


def hash_api_key(plain_key: str) -> str:
    """Deterministic SHA-256 hex digest, used for storage + lookup."""
    return hashlib.sha256(plain_key.encode("utf-8")).hexdigest()


def key_display_parts(plain_key: str) -> tuple[str, str]:
    """Return (prefix, last_four) for masked display, e.g.

        generate_api_key() -> "tac_live_9f3aK7...52b1"
        key_display_parts(...) -> ("tac_live_9f3a", "52b1")

    so the UI can later render "tac_live_9f3a...52b1" without ever
    holding onto the full key again.
    """
    body = plain_key[len(_KEY_PREFIX) + 1 :]
    prefix = f"{_KEY_PREFIX}_{body[:_PREFIX_VISIBLE_CHARS]}"
    last_four = plain_key[-4:]
    return prefix, last_four


__all__ = ["generate_api_key", "hash_api_key", "key_display_parts"]